# docker-compose.yml

version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: app_db
  #     POSTGRES_USER: app_user
  #     POSTGRES_PASSWORD: password
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"
